### ISSUE TITLE
Close the picker when date is selected

### ISSUE THREAD

**Issue by mtellezj** [PanagiotisGeorgiadis/ElmDatePicker#16]
Is there a way to close withInput's picker when a date/range-date is selected? Right now I need to click outside of the picker to close it. Any help is welcome.

**Comment by PanagiotisGeorgiadis** [comment]
Hello @mtellezj!

The examples are using a [subscription](https://github.com/PanagiotisGeorgiadis/Elm-DatePicker-examples/blob/master/src/Components/WithInput/Single/DatePicker.elm#L76) to the `Browser.onClick` event in order to hide / close the `DatePicker`.

We can easily incorporate the same logic in the `PickerMsg` in our `update` function.
For example, the `PickerMsg` on the [Single DatePicker example](https://github.com/PanagiotisGeorgiadis/Elm-DatePicker-examples/blob/master/src/Components/WithInput/Single/DatePicker.elm#L84) can be transformed like:

```elm

PickerMsg subMsg ->
    let
        ( updated, subCmd, extMsg ) =
            DatePicker.update subMsg model.picker

        selectedDateTime =
            case extMsg of
                DatePicker.None ->
                    model.selectedDateTime

                DatePicker.DateSelected dateTime ->
                    dateTime
    in
    (  {  model
           | picker = updated
           , selectedDateTime = selectedDateTime
           -- `isFocused` is controlling whether to show the `DatePicker` or not in our examples, so we can 
           -- toggle it when we deem necessary.
           , isFocused =
               case selectedDateTime of
                   Just _ ->
                       False

                   Nothing ->
                       True
        }
    , Cmd.map PickerMsg subCmd
    )
```

Let me know if the above make sense

**Comment by mtellezj** [comment]
Hi @PanagiotisGeorgiadis! I modify my code as per your suggestion, it works but only for the _first time_. When I select a date, the picker is closed but now  this code
```elm
case selectedDateTime of
    Just _ ->
        False

    Nothing ->
        True
```
always return `True` because there is already a selected date, so I can't change the date. If the input box lost focus and then I click on it, the picker show up (by `FocusHandler`) but when I hover over the picker it get closed because `PickerMsg subMsg` set `isFocused` to `False`. I make it work with your code and modifying `FocusHandler` (I'm using a DateRangePicker by the way):
```elm
FocusHandler ->
    let
        updated = DateRangePicker.resetSelectedDateRange model.picker
    in
    ( { model | isFocused = True
                , selectedRange = Nothing
                , picker = updated
        }
    , Cmd.none
    )
```
It feels hacky but works. Is there a better way? I try to attach to `selectDate`message, but this get fired when you click  start and end date. Maybe a `selectRangeDone` message that only is fired when both start and end dates are clicked, so I can set `isFocused = False`. Any thoughts are welcome.

**Comment by PanagiotisGeorgiadis** [comment]
Hello @mtellezj, on the `DateRange` Pickers the behavior is a bit different cause we are waiting for a `dateRange` to be selected.

The [Single DateRangePicker example](https://github.com/PanagiotisGeorgiadis/Elm-DatePicker-examples/blob/master/src/Components/WithInput/Single/DateRangePicker.elm#L85) can be modified as follows in order to incorporate what you need:
```elm
PickerMsg subMsg ->
    let
        ( updated, subCmd, extMsg ) =
            DateRangePicker.update subMsg model.picker

        ( selectedRange, isFocused ) =
            case extMsg of
                DateRangePicker.None ->
                    ( model.selectedRange, True )

                DateRangePicker.DateRangeSelected dateRange ->
                    ( dateRange
                    , case dateRange of
                        Just range ->
                            False

                        Nothing ->
                            True
                    )
    in
    ( { model
         | picker = updated
         , selectedRange = selectedRange
         , isFocused = isFocused
       }
    , Cmd.map PickerMsg subCmd
    )
```

**Comment by mtellezj** [comment]
@PanagiotisGeorgiadis Thanks a lot! That works exactly like I want it. Cheers!
